services:
  web:
    container_name: ${CONTAINER_NAME:-marina_web}
    image: ${IMAGE_NAME:-marina_image}
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - ${DB_DIR:-./data}:/app/data
    ports:
      - "${WEB_PORT:-8004}:8000"
    env_file:
      - .env
    restart: always
