# Generated by Django 4.2.30 on 2026-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_at_sea',
            field=models.BooleanField(default=False, help_text='Set to true if long-term tenant is away and berth can be sub-leased', verbose_name='At Sea'),
        ),
    ]
