# Generated by Django 4.2.30 on 2026-05-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0002_bookingservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(default='DE', help_text='ISO Language Code (DE, EN, etc.)', max_length=2, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(default='DE', help_text='ISO Country Code (DE, GR, US, etc.)', max_length=2, verbose_name='Nationality'),
        ),
    ]
