# Generated by Django 4.2.30 on 2026-05-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0003_customer_language_customer_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='boat_type',
            field=models.CharField(choices=[('SAIL', 'Sailing Yacht'), ('MOTOR', 'Motorboat'), ('CAT', 'Catamaran'), ('RIB', 'RIB / Zodiac'), ('OTHER', 'Other')], default='SAIL', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='boat',
            name='diesel_tank',
            field=models.IntegerField(default=0, verbose_name='Diesel Tank (L)'),
        ),
        migrations.AddField(
            model_name='boat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boats/', verbose_name='Boat Photo'),
        ),
        migrations.AddField(
            model_name='boat',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Last Maintenance'),
        ),
        migrations.AddField(
            model_name='boat',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Technical Notes'),
        ),
        migrations.AddField(
            model_name='boat',
            name='water_tank',
            field=models.IntegerField(default=0, verbose_name='Water Tank (L)'),
        ),
        migrations.AddField(
            model_name='boat',
            name='year_built',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year Built'),
        ),
    ]
