# Generated by Django 4.2.30 on 2026-05-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0004_boat_boat_type_boat_diesel_tank_boat_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='color',
            field=models.CharField(default='#3498db', help_text='Hex color for timeline', max_length=7, verbose_name='Color'),
        ),
    ]
