# Generated by Django 4.2.30 on 2026-05-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0005_boat_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(help_text="e.g. 'de', 'gr'", max_length=2, unique=True, verbose_name='ISO Code')),
                ('name', models.CharField(help_text="e.g. 'Germany'", max_length=100, verbose_name='Country Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['iso_code'],
            },
        ),
    ]
