# Generated by Django 4.2.30 on 2026-05-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0006_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='draft',
            field=models.FloatField(default=0.0, help_text='Draft in meters', verbose_name='Draft (meters)'),
        ),
        migrations.AddField(
            model_name='boat',
            name='engine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Engine'),
        ),
        migrations.AddField(
            model_name='boat',
            name='width',
            field=models.FloatField(default=0.0, help_text='Width in meters', verbose_name='Width (meters)'),
        ),
    ]
