# Generated by Django 4.2.30 on 2026-05-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0007_boat_draft_boat_engine_boat_width'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricerate',
            options={'ordering': ['from_meters'], 'verbose_name': 'Price Rate', 'verbose_name_plural': 'Price Rates'},
        ),
        migrations.RemoveField(
            model_name='pricerate',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='pricerate',
            name='price_per_meter_day',
        ),
        migrations.AddField(
            model_name='pricerate',
            name='from_meters',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='From Meters'),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Price per Day'),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='to_meters',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='To Meters'),
        ),
    ]
