# Generated by Django 4.2.30 on 2026-05-08 05:50

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0008_alter_pricerate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='color',
            field=colorfield.fields.ColorField(default='#3498db', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price per Unit'),
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.CharField(choices=[('HARBORMASTER', 'Harbormaster'), ('EXTERNAL', 'External Partner'), ('CRAFTSMAN', 'Craftsman / Mechanic')], default='HARBORMASTER', max_length=20, verbose_name='Provider / Supplier'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('SUPPLY', 'Supply (Water, Electricity, etc.)'), ('MAINTENANCE', 'Maintenance & Repair'), ('CLEANING', 'Cleaning'), ('ADMINISTRATIVE', 'Administrative'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Service Type'),
        ),
        migrations.AddField(
            model_name='service',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Tax Rate (%)'),
        ),
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.CharField(choices=[('LITER', 'Liter'), ('KG', 'Kilogram'), ('KWH', 'kWh'), ('HOUR', 'Hour'), ('PIECE', 'Piece / Unit')], default='PIECE', max_length=10, verbose_name='Unit'),
        ),
    ]
