# Generated by Django 4.2.30 on 2026-05-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0009_remove_service_price_service_color_service_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes for Provider'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per Unit (At Booking)'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tax Rate (%)'),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='quantity',
            field=models.FloatField(default=1.0, verbose_name='Quantity / Units'),
        ),
    ]
