# Generated by Django 4.2.30 on 2026-05-08 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0010_bookingservice_notes_bookingservice_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='boat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='marina.boat'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='marina.customer'),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='marina.booking'),
        ),
    ]
