# Generated by Django 4.2.30 on 2026-05-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0011_bookingservice_boat_bookingservice_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(choices=[('LITER', 'Liter'), ('KG', 'Kilogram'), ('KWH', 'kWh'), ('HOUR', 'Hour'), ('DAY', 'Day(s)'), ('PIECE', 'Piece / Unit')], default='PIECE', max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.CharField(choices=[('LITER', 'Liter'), ('KG', 'Kilogram'), ('KWH', 'kWh'), ('HOUR', 'Hour'), ('DAY', 'Day(s)'), ('PIECE', 'Piece / Unit')], default='PIECE', max_length=10, verbose_name='Unit'),
        ),
    ]
