# Generated by Django 4.2.30 on 2026-05-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0013_serviceprovider_alter_service_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boat',
            options={'ordering': ['name'], 'verbose_name': 'Boat', 'verbose_name_plural': 'Boats'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
