# Generated by Django 4.2.30 on 2026-05-13 10:34

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0015_block_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berth',
            options={'ordering': ['block', models.OrderBy(django.db.models.functions.text.Length('number')), 'number'], 'verbose_name': 'Berth', 'verbose_name_plural': 'Berths'},
        ),
    ]
