# Generated by Django 4.2.30 on 2026-05-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0016_alter_berth_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='scheduled_end',
            field=models.DateField(blank=True, null=True, verbose_name='Scheduled End'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='scheduled_start',
            field=models.DateField(blank=True, null=True, verbose_name='Scheduled Start'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='workload_hours',
            field=models.FloatField(default=0.0, verbose_name='Workload (Hours)'),
        ),
    ]
