# Generated by Django 4.2.30 on 2026-05-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0017_bookingservice_scheduled_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('WATER', 'Water Berth'), ('SERVICE', 'Service / Dry-Dock'), ('LAND', 'Land Storage')], default='WATER', max_length=10),
        ),
    ]
