# Generated by Django 4.2.30 on 2026-05-13 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0018_block_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='berth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='marina.berth'),
        ),
    ]
