# Generated by Django 4.2.30 on 2026-05-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0019_bookingservice_berth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingservice',
            options={'verbose_name': 'Service Auftrag', 'verbose_name_plural': 'Service Aufträge'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service Katalog', 'verbose_name_plural': 'Service Katalog'},
        ),
    ]
