# Generated by Django 4.2.30 on 2026-05-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0020_alter_bookingservice_options_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingservice',
            options={'verbose_name': 'Service Order', 'verbose_name_plural': 'Service Orders'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service Catalog', 'verbose_name_plural': 'Service Catalog'},
        ),
    ]
