# Generated by Django 4.2.30 on 2026-05-13 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0022_serviceorder_bookingservice_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0, verbose_name='Quantity / Units')),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per Unit (At Booking)')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tax Rate (%)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marina.serviceorder')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.service')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.DeleteModel(
            name='BookingService',
        ),
    ]
