# Generated by Django 4.2.30 on 2026-05-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0023_serviceorderitem_delete_bookingservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mydata_mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
