# Generated by Django 4.2.30 on 2026-05-14 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0024_invoice_mydata_mark_invoice_mydata_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0, verbose_name='Quantity / Units')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per Unit')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tax Rate (%)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='marina.booking')),
                ('service', models.ForeignKey(limit_choices_to={'service_type': 'SUPPLY'}, on_delete=django.db.models.deletion.CASCADE, to='marina.service')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('berth', models.ForeignKey(blank=True, help_text='Dry dock or work place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='marina.berth')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='marina.boat')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='marina.customer')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0, verbose_name='Quantity / Units')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per Unit (At Order)')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tax Rate (%)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marina.workorder')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.service')),
            ],
            options={
                'verbose_name': 'Work Order Item',
                'verbose_name_plural': 'Work Order Items',
            },
        ),
        migrations.RemoveField(
            model_name='serviceorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='serviceorderitem',
            name='service',
        ),
        migrations.DeleteModel(
            name='ServiceOrder',
        ),
        migrations.DeleteModel(
            name='ServiceOrderItem',
        ),
    ]
