# Generated by Django 4.2.30 on 2026-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0025_bookingsupply_workorder_workorderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('SUPPLY', 'Supply (Water, Electricity, etc.)'), ('MAINTENANCE', 'Maintenance & Repair'), ('PART', 'Spare Part / Material'), ('CLEANING', 'Cleaning'), ('ADMINISTRATIVE', 'Administrative'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Service Type'),
        ),
    ]
