# Generated by Django 4.2.30 on 2026-05-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0027_servicecategory_remove_service_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsupply',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.service'),
        ),
    ]
