# Generated by Django 4.2.30 on 2026-05-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0028_alter_bookingsupply_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Office / DOY'),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT Number / AFM'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('RECEIPT', 'Retail Sales Receipt (Απόδειξη Λιανικής Πώλησης)'), ('INVOICE', 'Service Invoice (Τιμολόγιο Παροχής Υπηρεσιών)')], default='RECEIPT', max_length=10),
        ),
    ]
