# Generated by Django 4.2.30 on 2026-05-28 20:15

from django.db import migrations

def create_walkin_customer(apps, schema_editor):
    Customer = apps.get_model('marina', 'Customer')
    Customer.objects.get_or_create(
        name='Laufkunde / Walk-In',
        defaults={
            'email': 'walkin@marina-samos.com',
            'nationality': 'GR',
            'language': 'EN'
        }
    )

def remove_walkin_customer(apps, schema_editor):
    Customer = apps.get_model('marina', 'Customer')
    Customer.objects.filter(name='Laufkunde / Walk-In').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0029_customer_tax_office_customer_vat_number_and_more'),
    ]

    operations = [
        migrations.RunPython(create_walkin_customer, remove_walkin_customer),
    ]
