# Generated by Django 4.2.30 on 2026-05-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0030_auto_20260528_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport Number'),
        ),
    ]
