# Generated by Django 4.2.30 on 2026-05-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0031_customer_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('RECEIPT', 'Retail Sales Receipt (Απόδειξη Λιανικής Πώλησης)'), ('TAXFREE', 'Retail Receipt - Tax Free (Απόδειξη Λιανικής - Tax Free)'), ('INVOICE', 'Service Invoice (Τιμολόγιο Παροχής Υπηρεσιών)')], default='RECEIPT', max_length=10),
        ),
    ]
