# Generated by Django 4.2.30 on 2026-05-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0033_alter_invoice_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('RECEIPT', 'Retail Sales Receipt'), ('TAXFREE', 'Retail Receipt - Tax Free'), ('INVOICE', 'Service Invoice (B2B)')], default='RECEIPT', max_length=10),
        ),
    ]
