# Generated by Django 4.2.30 on 2026-05-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0035_alter_customer_tax_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ORMOS MARINA', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('address', models.TextField(default='Ormos Marathokampou Marina,\nSamos Island, 81002, Greece')),
                ('opening_hours', models.CharField(default='08:00 - 20:00', max_length=100)),
                ('email', models.EmailField(default='ormosmarina@aris-samos.com', max_length=254)),
                ('phone', models.CharField(default='+49 163 3430354', max_length=50)),
                ('vat_number', models.CharField(default='888888888', max_length=50)),
                ('tax_office', models.CharField(default='Samos', help_text='e.g. DOY Samos', max_length=100)),
                ('invoice_footer', models.TextField(default='Thank you for choosing Ormos Marina. Safe travels!', help_text='Custom thank-you message on the bottom of invoices')),
                ('marina_svg', models.TextField(blank=True, help_text='Paste raw SVG map code here to dynamically render berths. If empty, the default static SVG will be used.', null=True)),
            ],
            options={
                'verbose_name': 'Tenant Configuration',
                'verbose_name_plural': 'Tenant Configurations',
            },
        ),
    ]
