# Generated by Django 4.2.30 on 2026-05-29 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marina', '0036_tenantconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMenuPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_dashboard', models.BooleanField(default=True, verbose_name='Show Dashboard')),
                ('show_calendar', models.BooleanField(default=True, verbose_name='Show Calendar')),
                ('show_berths', models.BooleanField(default=True, verbose_name='Show Berths')),
                ('show_customers', models.BooleanField(default=True, verbose_name='Show Customers')),
                ('show_bookings', models.BooleanField(default=True, verbose_name='Show Bookings')),
                ('show_planning', models.BooleanField(default=True, verbose_name='Show Planning')),
                ('show_service', models.BooleanField(default=True, verbose_name='Show Service')),
                ('show_invoices', models.BooleanField(default=True, verbose_name='Show Invoices')),
                ('show_reports', models.BooleanField(default=True, verbose_name='Show Reports')),
                ('allow_dashboard', models.BooleanField(default=True, verbose_name='Allow Dashboard')),
                ('allow_calendar', models.BooleanField(default=True, verbose_name='Allow Calendar')),
                ('allow_berths', models.BooleanField(default=True, verbose_name='Allow Berths')),
                ('allow_customers', models.BooleanField(default=True, verbose_name='Allow Customers')),
                ('allow_bookings', models.BooleanField(default=True, verbose_name='Allow Bookings')),
                ('allow_planning', models.BooleanField(default=True, verbose_name='Allow Planning')),
                ('allow_service', models.BooleanField(default=True, verbose_name='Allow Service')),
                ('allow_invoices', models.BooleanField(default=True, verbose_name='Allow Invoices')),
                ('allow_reports', models.BooleanField(default=True, verbose_name='Allow Reports')),
                ('allow_admin', models.BooleanField(default=False, verbose_name='Allow Admin Link')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Menu Preference',
                'verbose_name_plural': 'User Menu Preferences',
            },
        ),
    ]
