# Generated by Django 4.2.30 on 2026-05-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0037_usermenupreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Subdomain Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Instance Name')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Owner Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
    ]
