# Generated by Django 4.2.30 on 2026-05-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0039_seed_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenupreference',
            name='show_company_name',
            field=models.BooleanField(default=True, verbose_name='Show Company Name in Header'),
        ),
    ]
