# Generated by Django 4.2.30 on 2026-06-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0040_usermenupreference_show_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='City / Postal Code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_at',
            field=models.TimeField(blank=True, help_text='Time of issue (ΩΡΑ ΑΠΟΣΤΟΛΗΣ)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('EL', 'Ελληνικά (Greek)'), ('DE', 'Deutsch (German)')], default='EN', help_text='Invoice PDF language', max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, help_text='ΠΑΡΑΤΗΡΗΣΕΙΣ – visible on invoice', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purpose',
            field=models.CharField(blank=True, help_text='ΣΚΟΠΟΣ ΔΙΑΚΙΝΗΣΗΣ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='series',
            field=models.CharField(blank=True, help_text='Document series (ΣΕΙΡΑ), e.g. 2ΑΠΥ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='ΕΚΠΤΩΣΗ %', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_code',
            field=models.CharField(blank=True, help_text='ΚΩΔΙΚΟΣ service code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=24.0, help_text='ΦΠΑ % (Greece default 24%, Samos 17%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='iban_1',
            field=models.CharField(blank=True, help_text='Primary IBAN', max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='iban_1_bank',
            field=models.CharField(blank=True, help_text='Primary bank name, e.g. Alpha Bank', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='iban_2',
            field=models.CharField(blank=True, help_text='Secondary IBAN', max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='iban_2_bank',
            field=models.CharField(blank=True, help_text='Secondary bank name, e.g. Piraeus Bank', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile / KIN number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Full legal owner name for invoice header', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='website',
            field=models.CharField(blank=True, help_text='e.g. www.aris-samos.com', max_length=200, null=True),
        ),
    ]
