# Generated by Django 4.2.30 on 2026-06-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0041_invoice_i18n_iban_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='address_el',
            field=models.TextField(blank=True, help_text='Address in Greek / Ελληνικά', null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='company_name_el',
            field=models.CharField(blank=True, help_text='Company name in Greek / Ελληνικά', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='iban_1_bank_el',
            field=models.CharField(blank=True, help_text='Primary bank name in Greek / Ελληνικά', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='iban_2_bank_el',
            field=models.CharField(blank=True, help_text='Secondary bank name in Greek / Ελληνικά', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='invoice_footer_el',
            field=models.TextField(blank=True, help_text='Custom thank-you message in Greek / Ελληνικά', null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='owner_name_el',
            field=models.CharField(blank=True, help_text='Full legal owner name in Greek / Ελληνικά', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='tax_office_el',
            field=models.CharField(blank=True, help_text='Tax office name in Greek / Ελληνικά (e.g. ΔΟΥ Σάμου)', max_length=100, null=True),
        ),
    ]
