# Generated by Django 4.2.30 on 2026-06-12 19:12

from django.db import migrations, models


def seed_vat_rates(apps, schema_editor):
    VatRateConfig = apps.get_model('marina', 'VatRateConfig')
    default_rates = [
        {'rate': 24.00, 'mydata_vat_category': 1, 'label': 'Standard rate (24%)'},
        {'rate': 13.00, 'mydata_vat_category': 2, 'label': 'Reduced rate (13%)'},
        {'rate': 6.00, 'mydata_vat_category': 3, 'label': 'Super reduced rate (6%)'},
        {'rate': 17.00, 'mydata_vat_category': 4, 'label': 'Samos standard rate (17%)'},
        {'rate': 9.00, 'mydata_vat_category': 5, 'label': 'Samos reduced rate (9%)'},
        {'rate': 4.00, 'mydata_vat_category': 6, 'label': 'Samos super reduced rate (4%)'},
        {'rate': 0.00, 'mydata_vat_category': 7, 'label': 'VAT exempt (0%)'},
    ]
    for r in default_rates:
        VatRateConfig.objects.get_or_create(
            rate=r['rate'],
            defaults={
                'mydata_vat_category': r['mydata_vat_category'],
                'label': r['label']
            }
        )

def reverse_seed_vat_rates(apps, schema_editor):
    VatRateConfig = apps.get_model('marina', 'VatRateConfig')
    VatRateConfig.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0042_tenantconfig_address_el_tenantconfig_company_name_el_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatRateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='e.g. 24.00, 17.00, 13.00', max_digits=5, unique=True, verbose_name='VAT Rate (%)')),
                ('mydata_vat_category', models.IntegerField(help_text='myDATA VAT Category code (e.g. 1: 24%, 2: 13%, 4: 17%, 7: 0%, etc.)', verbose_name='myDATA VAT Category Code')),
                ('label', models.CharField(help_text='e.g. Standard rate, Samos reduced standard rate, etc.', max_length=100, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'VAT Rate Configuration',
                'verbose_name_plural': 'VAT Rate Configurations',
                'ordering': ['-rate'],
            },
        ),
        migrations.RunPython(seed_vat_rates, reverse_seed_vat_rates),
    ]
